image: node:6

cache:
  paths:
    - node_modules/

before_script:
  - npm i -g yarn
  - yarn

pages:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - master
