image: node:6

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm prune

pages:
  stage: deploy
  script:
    - npm run prod
  artifacts:
    paths:
      - public
  only:
    - master
